//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Öğrenci_Not_Kayıt_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ders
    {
        public short OgrId { get; set; }
        public string OgrNumara { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public Nullable<byte> OgrS1 { get; set; }
        public Nullable<byte> OgrS2 { get; set; }
        public Nullable<byte> OgrS3 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
